name       : ibus-rime
version    : 1.5.0
release    : 1
source     :
    - https://github.com/rime/ibus-rime/archive/refs/tags/1.5.0.tar.gz : e633bde71055b9298837c7fdd73c5694594633e08bf58b6e5cf17bac4959dacb
license    : GPL-3.0-or-later
component  : desktop.core
summary    : Rime for Linux/IBus.
description: |
    Rime Input Method Engine for Linux/IBus.
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(rime)
setup      : |
    %cmake_ninja -DDRIME_DATA_DIR=/usr/share/rime-data
build      : |
    %ninja_build
install    : |
    %ninja_install
