name       : ibus-rime
version    : 1.5.0
release    : 4
source     :
    - https://github.com/rime/ibus-rime/archive/refs/tags/1.5.0.tar.gz : e633bde71055b9298837c7fdd73c5694594633e08bf58b6e5cf17bac4959dacb
    - git|https://github.com/rime/plum : 3d06432dda5fd1738bebda298c574b6ed2d512d8
license    : GPL-3.0-or-later
component  : desktop.core
summary    : Rime for Linux/IBus.
description: |
    Rime Input Method Engine for Linux/IBus.
networking : yes
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(rime)
setup      : |
    cp -R $sources/plum.git plum && pushd plum
    # Can't use macro because of https://github.com/rime/plum/issues/29
    make all-bin
    %make_install
    popd

    # Make sure Rime's typing dialog's orientation follows the user's IBus setting.
    sed -i "s/horizontal:/# horizontal:/" ibus_rime.yaml

    %cmake_ninja -DRIME_DATA_DIR=/usr/share/rime-data
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Install plum, Rime's input schema manager.
    install -Dm00755 plum/rime-install -t $installdir/usr/bin
